/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_LibXml */

#ifndef _Included_rath_libxml_LibXml
#define _Included_rath_libxml_LibXml
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rath_libxml_LibXml
 * Method:    parseFileImpl
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_rath_libxml_LibXml_parseFileImpl
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
