/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_XPathExpression */

#ifndef _Included_rath_libxml_XPathExpression
#define _Included_rath_libxml_XPathExpression
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
