/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_Document */

#ifndef _Included_rath_libxml_Document
#define _Included_rath_libxml_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rath_libxml_Document
 * Method:    getRootElementImpl
 * Signature: ()Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Document_getRootElementImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Document
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Document_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
