/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_Node_Type */

#ifndef _Included_rath_libxml_Node_Type
#define _Included_rath_libxml_Node_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
