/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xmlsoft_XPathObject */

#ifndef _Included_org_xmlsoft_XPathObject
#define _Included_org_xmlsoft_XPathObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xmlsoft_XPathObject
 * Method:    castToStringImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xmlsoft_XPathObject_castToStringImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_XPathObject
 * Method:    castToNumberImpl
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_xmlsoft_XPathObject_castToNumberImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_XPathObject
 * Method:    castToBooleanImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xmlsoft_XPathObject_castToBooleanImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_XPathObject
 * Method:    disposeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_XPathObject_disposeImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
