/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xmlsoft_XPathContext */

#ifndef _Included_org_xmlsoft_XPathContext
#define _Included_org_xmlsoft_XPathContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xmlsoft_XPathContext
 * Method:    addNamespaceImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_XPathContext_addNamespaceImpl
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xmlsoft_XPathContext
 * Method:    evaluateImpl
 * Signature: (Ljava/lang/String;)Lorg/xmlsoft/XPathObject;
 */
JNIEXPORT jobject JNICALL Java_org_xmlsoft_XPathContext_evaluateImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xmlsoft_XPathContext
 * Method:    evaluateCompiledImpl
 * Signature: (Lorg/xmlsoft/XPathExpression;)Lorg/xmlsoft/XPathObject;
 */
JNIEXPORT jobject JNICALL Java_org_xmlsoft_XPathContext_evaluateCompiledImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xmlsoft_XPathContext
 * Method:    disposeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_XPathContext_disposeImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_XPathContext
 * Method:    setContextNodeImpl
 * Signature: (Lorg/xmlsoft/Node;)V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_XPathContext_setContextNodeImpl
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
