/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xmlsoft_LibXml */

#ifndef _Included_org_xmlsoft_LibXml
#define _Included_org_xmlsoft_LibXml
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xmlsoft_LibXml
 * Method:    initInternalParser
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_LibXml_initInternalParser
  (JNIEnv *, jclass);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    parseFileImpl
 * Signature: (Ljava/lang/String;)Lorg/xmlsoft/Document;
 */
JNIEXPORT jobject JNICALL Java_org_xmlsoft_LibXml_parseFileImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    parseStringImpl
 * Signature: (Ljava/lang/String;)Lorg/xmlsoft/Document;
 */
JNIEXPORT jobject JNICALL Java_org_xmlsoft_LibXml_parseStringImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    parseSystemIdImpl
 * Signature: (Ljava/lang/String;Ljava/io/InputStream;)Lorg/xmlsoft/Document;
 */
JNIEXPORT jobject JNICALL Java_org_xmlsoft_LibXml_parseSystemIdImpl
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    parseSAXImpl
 * Signature: (Ljava/lang/String;Lorg/xmlsoft/SAXHandlerEngine;I)V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_LibXml_parseSAXImpl
  (JNIEnv *, jclass, jstring, jobject, jint);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    parseSAXFileImpl
 * Signature: (Ljava/lang/String;Lorg/xmlsoft/SAXHandlerEngine;I)V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_LibXml_parseSAXFileImpl
  (JNIEnv *, jclass, jstring, jobject, jint);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    parseSAXSystemIdImpl
 * Signature: (Ljava/lang/String;Ljava/io/InputStream;Lorg/xmlsoft/SAXHandlerEngine;I)V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_LibXml_parseSAXSystemIdImpl
  (JNIEnv *, jclass, jstring, jobject, jobject, jint);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    compileXPathImpl
 * Signature: (Ljava/lang/String;)Lorg/xmlsoft/XPathExpression;
 */
JNIEXPORT jobject JNICALL Java_org_xmlsoft_LibXml_compileXPathImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_xmlsoft_LibXml
 * Method:    printTcmallocStatImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_LibXml_printTcmallocStatImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
