/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xmlsoft_XPathExpression */

#ifndef _Included_org_xmlsoft_XPathExpression
#define _Included_org_xmlsoft_XPathExpression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xmlsoft_XPathExpression
 * Method:    disposeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xmlsoft_XPathExpression_disposeImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
