/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xmlsoft_impl_LocatorImpl */

#ifndef _Included_org_xmlsoft_impl_LocatorImpl
#define _Included_org_xmlsoft_impl_LocatorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xmlsoft_impl_LocatorImpl
 * Method:    getPublicIdImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xmlsoft_impl_LocatorImpl_getPublicIdImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_impl_LocatorImpl
 * Method:    getSystemIdImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xmlsoft_impl_LocatorImpl_getSystemIdImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_impl_LocatorImpl
 * Method:    getLineNumberImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_xmlsoft_impl_LocatorImpl_getLineNumberImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_xmlsoft_impl_LocatorImpl
 * Method:    getColumnNumberImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_xmlsoft_impl_LocatorImpl_getColumnNumberImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
