/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_Node */

#ifndef _Included_rath_libxml_Node
#define _Included_rath_libxml_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rath_libxml_Node
 * Method:    childrenImpl
 * Signature: ()Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_childrenImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    fillNamespaceImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_fillNamespaceImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    fillNameImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_fillNameImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    fillRequiredFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_fillRequiredFields
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    nextImpl
 * Signature: ()Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_nextImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_rath_libxml_Node_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    previousImpl
 * Signature: ()Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_previousImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    getParentImpl
 * Signature: ()Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_getParentImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    getLastImpl
 * Signature: ()Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_getLastImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    getTextImpl
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rath_libxml_Node_getTextImpl
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     rath_libxml_Node
 * Method:    getPropImpl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rath_libxml_Node_getPropImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rath_libxml_Node
 * Method:    fillAttributeNodes
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_fillAttributeNodes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    fillAttributeNames
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_fillAttributeNames
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    getNsPropImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rath_libxml_Node_getNsPropImpl
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     rath_libxml_Node
 * Method:    setPropImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_setPropImpl
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     rath_libxml_Node
 * Method:    removePropImpl
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_rath_libxml_Node_removePropImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rath_libxml_Node
 * Method:    addChildImpl
 * Signature: (Lrath/libxml/Node;)Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_addChildImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    unlinkImpl
 * Signature: (Lrath/libxml/Node;)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_unlinkImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    disposeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_disposeImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_Node
 * Method:    setTextImpl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_Node_setTextImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rath_libxml_Node
 * Method:    addPrevSiblingImpl
 * Signature: (Lrath/libxml/Node;)Lrath/libxml/Node;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_Node_addPrevSiblingImpl
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
