/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_LibXml */

#ifndef _Included_rath_libxml_LibXml
#define _Included_rath_libxml_LibXml
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rath_libxml_LibXml
 * Method:    initInternalParser
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_LibXml_initInternalParser
  (JNIEnv *, jclass);

/*
 * Class:     rath_libxml_LibXml
 * Method:    parseFileImpl
 * Signature: (Ljava/lang/String;)Lrath/libxml/Document;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_LibXml_parseFileImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     rath_libxml_LibXml
 * Method:    parseStringImpl
 * Signature: (Ljava/lang/String;)Lrath/libxml/Document;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_LibXml_parseStringImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     rath_libxml_LibXml
 * Method:    parseSAXImpl
 * Signature: (Ljava/lang/String;Lrath/libxml/impl/SAXHandlerInternal;I)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_LibXml_parseSAXImpl
  (JNIEnv *, jclass, jstring, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
