/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_XPathObject */

#ifndef _Included_rath_libxml_XPathObject
#define _Included_rath_libxml_XPathObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rath_libxml_XPathObject
 * Method:    castToStringImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rath_libxml_XPathObject_castToStringImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_XPathObject
 * Method:    castToNumberImpl
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_rath_libxml_XPathObject_castToNumberImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_XPathObject
 * Method:    castToBooleanImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_rath_libxml_XPathObject_castToBooleanImpl
  (JNIEnv *, jobject);

/*
 * Class:     rath_libxml_XPathObject
 * Method:    disposeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_XPathObject_disposeImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
