/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rath_libxml_XPathContext */

#ifndef _Included_rath_libxml_XPathContext
#define _Included_rath_libxml_XPathContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rath_libxml_XPathContext
 * Method:    addNamespaceImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rath_libxml_XPathContext_addNamespaceImpl
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     rath_libxml_XPathContext
 * Method:    evaluateImpl
 * Signature: (Ljava/lang/String;)Lrath/libxml/XPathObject;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_XPathContext_evaluateImpl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     rath_libxml_XPathContext
 * Method:    evaluateCompiledImpl
 * Signature: (Lrath/libxml/XPathExpression;)Lrath/libxml/XPathObject;
 */
JNIEXPORT jobject JNICALL Java_rath_libxml_XPathContext_evaluateCompiledImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     rath_libxml_XPathContext
 * Method:    disposeImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rath_libxml_XPathContext_disposeImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
